services:
  react-frontend:
    image: react:latest
    ports:
      - 5010:5010
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
  go-backend:
    image: go:latest
    ports:
      - 8080:8080
    environment:
      - REQUEST_ORIGIN=http://localhost:5010
