services:
  react-frontend:
    image: react:latest
    ports:
      - 5010:5010
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080

  go-backend:
    image: go:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - REQUEST_ORIGIN=http://localhost:5010
      - REDIS_HOST=redis-cache
    networks:
      - private-network

  redis-cache:
    image: redis:8.4-alpine
    networks:
      - private-network

networks:
  private-network:
    driver: bridge
