services:
  react-frontend:
    image: react:latest
    build:
      context: ./react-frontend
      dockerfile: Dockerfile
    # ports:
    #   - 5010:5010
    # environment:
    #   - REACT_APP_BACKEND_URL=http://localhost:8080
    networks:
      - private-network

  go-backend:
    image: go:latest
    build:
      context: ./go-backend
      dockerfile: Dockerfile
    restart: unless-stopped
    # ports:
    #   - 8080:8080
    environment:
      # - REQUEST_ORIGIN=http://localhost:5010
      - REQUEST_ORIGIN=http://localhost
      - REDIS_HOST=redis-cache
      - POSTGRES_HOST=postgres-db
    networks:
      - private-network

  redis-cache:
    image: redis:8.4-alpine
    networks:
      - private-network

  postgres-db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    container_name: db_example
    volumes:
      # Bind mount (./database:) or Docker managed volume (database:)
      - ./database:/var/lib/postgresql/data
    networks:
      - private-network

  nginx-proxy:
    image: nginx:1.27-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - react-frontend
      - go-backend
    networks:
      - private-network

networks:
  private-network:
    driver: bridge
