version: "3.7"

services:
  node-dev-env:
    build: .
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules # A bit of node magic, this ensures the dependencies built for the image are not available locally.
    container_name: node-dev-env

volumes:
  node_modules:
