services:
  express-app:
    image: accentut/helsinki-do-express-app
    container_name: helsinki-do-express-app
    ports:
      - 8080:8080
  watchtower:
    image: containrrr/watchtower:latest
    environment:
      - WATCHTOWER_POLL_INTERVAL=60 # Poll every 60 seconds
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
